###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"

services:
    memcached:
        image: memcached:alpine
        container_name: bc-memcached

    redis:
        image: redis:alpine
        restart: always
        container_name: bc-redis

    elasticsearch:
        image: elasticsearch:5.4-alpine
        container_name: bc-elasticsearch

    webserver:
        image: nginx:alpine
        container_name: bc-webserver
        working_dir: /application
        volumes:
            - app_sync:/application:nocopy
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
            - elasticsearch
            - redis
        expose:
            - "9000"
        ports:
            - "8000:80"
        environment:
            PHP_XDEBUG_ENABLED: 1
            PHP_IDE_CONFIG: "serverName=localhost"
            XDEBUG_CONFIG: "idekey=PHPSTORM;remote_host=10.1.1.116" #10.254.254.254

    php-fpm:
        build: phpdocker/php-fpm
        container_name: bc-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

volumes:
    app_sync:
        external: true
    dbdata:
