###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
volumes:
    app_sync:
        external: true
services:

    redis:
      image: redis:alpine
      restart: always
      container_name: brucesays-chucksays-redis

    mysql:
      image: mysql:5.7
      container_name: brucesays-chucksays-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=db
        - MYSQL_USER=root
        - MYSQL_PASSWORD=toor
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: brucesays-chucksays-webserver
      working_dir: /application
      volumes:
          - app_sync:/application:rw
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: brucesays-chucksays-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
